### ISSUE TITLE
Cannot attach files to works in demo instance

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#1100]
File uploads aren't working on the demo instance.

My speculation is that https://github.com/projecthydra-labs/hyrax/pull/918 is at fault, though it's not obvious what might be going wrong because there are no honeybadger errors.

After a few retries, messages for the ContenDepositEventJob and AttachFilesToWorkJob wind up in the dead letter queue in SQS.

**Comment by jcoyne** [comment]
I'm postulating that background workers are not working at all.  In the error logs there are lots of messages like this:

```
F, [2017-05-15T13:00:07.797778 #24797] FATAL -- : [f77d5a97-d533-4fcb-80e8-1df0d33aae8d] ActionController::RoutingError (No route matches [POST] "/"):
F, [2017-05-15T13:00:07.797816 #24797] FATAL -- : [f77d5a97-d533-4fcb-80e8-1df0d33aae8d]   
F, [2017-05-15T13:00:07.797844 #24797] FATAL -- : [f77d5a97-d533-4fcb-80e8-1df0d33aae8d] actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] rack (2.0.2) lib/rack/method_override.rb:22:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] rack (2.0.2) lib/rack/runtime.rb:22:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] rack (2.0.2) lib/rack/sendfile.rb:111:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] secure_headers (3.6.4) lib/secure_headers/middleware.rb:12:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:34:in `block in call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] honeybadger (3.1.2) lib/honeybadger/agent.rb:321:in `with_rack_env'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:31:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] honeybadger (3.1.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] honeybadger (3.1.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] railties (5.0.2) lib/rails/engine.rb:522:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] puma (3.8.2) lib/puma/configuration.rb:224:in `call'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] puma (3.8.2) lib/puma/server.rb:435:in `process_client'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] puma (3.8.2) lib/puma/server.rb:299:in `block in run'
[f77d5a97-d533-4fcb-80e8-1df0d33aae8d] puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mjgiarlo** [comment]
I bet you're right, @jcoyne. There are jobs in the DLQ that are unrelated to the changes I made to file attachment, e.g., event jobs. This is consistent with your postulation.

**Comment by mjgiarlo** [comment]
Are you inclined to take this on, @jcoyne?

**Comment by jcoyne** [comment]
The problem here that our patch to ActiveJob (https://github.com/projecthydra-labs/hyku/blob/master/lib/active_job_tenant.rb#L11) is no longer applied after this change: https://github.com/projecthydra-labs/hyku/commit/91e36dbeb2d16867b910ba4efdb99c30b7bfa6f4#diff-f17c24f6e628b72f62542cfcc63d8031R6

**Comment by jcoyne** [comment]
There are reports in slack that this also affects the docker install.
