### ISSUE TITLE
[HyBox/production] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "sipity_entities_proxy_for_global_id"

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#746]
DETAIL:  Key (proxy_for_global_id)=(gid://hyku/GenericWork/gc691hc1079) already exists.: INSERT INTO "sipity_entities" ("proxy_for_global_id", "workflow_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"

## Backtrace

    line 26 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 42 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32605762)

```
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/services/hyrax/workflow/workflow_factory.rb:33 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/services/hyrax/workflow/workflow_factory.rb:13 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/initialize_workflow_actor.rb:15 :in `create_workflow`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/initialize_workflow_actor.rb:8 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/base_actor.rb:15 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/apply_permission_template_actor.rb:7 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/default_admin_set_actor.rb:9 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/interpret_visibility_actor.rb:85 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/abstract_actor.rb:25 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/attach_files_actor.rb:8 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/assign_representative_actor.rb:5 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/add_to_work_actor.rb:6 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/add_as_member_of_collections_actor.rb:6 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/create_with_files_actor.rb:6 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/create_with_remote_files_actor.rb:6 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/abstract_actor.rb:25 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/actors/hyrax/actors/actor_stack.rb:22 :in `create`
[GEM_ROOT]/bundler/gems/hyrax-4aff3e66264d/app/jobs/create_work_job.rb:19 :in `perform` 
```

**Comment by jeremyf** [comment]
Kicking around the idea of placing a transaction around the actor execution

https://github.com/projecthydra-labs/hyrax/blob/d90fce3d5c63e3733878344dee979ed8d6eee5a1/app/actors/hyrax/actors/actor_stack.rb#L20-L37

**Comment by jcoyne** [comment]
This is curious, we're now seeing this even with the transactional actor.  Maybe we need a mutex for running the actor stack?

**Comment by jeremyf** [comment]
Was the change deployed?

**Comment by jcoyne** [comment]
@jeremyf yep, here's the trace:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "sipity_entities_proxy_for_global_id" DETAIL: Key (proxy_for_global_id)=(gid://hyku/GenericWork/fp908wk8377) already exists. : INSERT INTO "sipity_entities" ("proxy_for_global_id", "workflow_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id" 
    postgresql_adapter.rb 598 block in exec_no_cache(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
    abstract_adapter.rb 589 block in log(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
    instrumenter.rb 21 instrument(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    abstract_adapter.rb 583 log(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'

    postgresql_adapter.rb 598 exec_no_cache(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
    postgresql_adapter.rb 587 execute_and_clear(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'
    database_statements.rb 103 exec_query(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
    database_statements.rb 137 exec_insert(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_insert'
    database_statements.rb 124 insert(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:124:in `insert'
    query_cache.rb 17 insert(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
    relation.rb 65 insert(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/relation.rb:65:in `insert'
    persistence.rb 560 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/persistence.rb:560:in `_create_record'
    counter_cache.rb 128 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/counter_cache.rb:128:in `_create_record'
    optimistic.rb 75 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    dirty.rb 123 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
    callbacks.rb 302 block in _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:302:in `block in _create_record'
    callbacks.rb 126 call(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
    callbacks.rb 506 block (2 levels) in compile(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
    callbacks.rb 455 call(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
    callbacks.rb 101 __run_callbacks__(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    callbacks.rb 750 _run_create_callbacks(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
    callbacks.rb 302 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:302:in `_create_record'
    timestamp.rb 68 _create_record(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/timestamp.rb:68:in `_create_record'
    persistence.rb 540 create_or_update(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/persistence.rb:540:in `create_or_update'
    callbacks.rb 298 block in create_or_update(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `block in create_or_update'
    callbacks.rb 126 call(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
    callbacks.rb 506 block (2 levels) in compile(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
    callbacks.rb 455 call(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
    callbacks.rb 101 __run_callbacks__(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    callbacks.rb 750 _run_save_callbacks(...)
    [GEM_ROOT]/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
    callbacks.rb 298 create_or_update(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
    persistence.rb 152 save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/persistence.rb:152:in `save!'
    validations.rb 50 save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/validations.rb:50:in `save!'
    dirty.rb 30 save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    transactions.rb 324 block in save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:324:in `block in save!'
    transactions.rb 395 block in with_transaction_returning_status(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    database_statements.rb 230 transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
    transactions.rb 211 transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
    transactions.rb 392 with_transaction_returning_status(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    transactions.rb 324 save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:324:in `save!'
    suppressor.rb 45 save!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/suppressor.rb:45:in `save!'
    persistence.rb 51 create!(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/persistence.rb:51:in `create!'
    workflow_factory.rb 33 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/services/hyrax/workflow/workflow_factory.rb:33:in `create'
    workflow_factory.rb 13 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/services/hyrax/workflow/workflow_factory.rb:13:in `create'
    initialize_workflow_actor.rb 15 create_workflow(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/initialize_workflow_actor.rb:15:in `create_workflow'
    initialize_workflow_actor.rb 8 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/initialize_workflow_actor.rb:8:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    base_actor.rb 15 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/base_actor.rb:15:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    apply_permission_template_actor.rb 7 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/apply_permission_template_actor.rb:7:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    default_admin_set_actor.rb 9 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/default_admin_set_actor.rb:9:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    interpret_visibility_actor.rb 85 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/interpret_visibility_actor.rb:85:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    abstract_actor.rb 25 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/abstract_actor.rb:25:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    attach_files_actor.rb 8 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/attach_files_actor.rb:8:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    assign_representative_actor.rb 5 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/assign_representative_actor.rb:5:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    add_to_work_actor.rb 6 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/add_to_work_actor.rb:6:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    add_as_member_of_collections_actor.rb 6 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/add_as_member_of_collections_actor.rb:6:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    create_with_files_actor.rb 6 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/create_with_files_actor.rb:6:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    create_with_remote_files_actor.rb 6 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/create_with_remote_files_actor.rb:6:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    abstract_actor.rb 25 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/abstract_actor.rb:25:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    transactional_request.rb 9 block in create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/transactional_request.rb:9:in `block in create'
    database_statements.rb 232 block in transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    transaction.rb 189 within_new_transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    database_statements.rb 232 transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    transactions.rb 211 transaction(...)
    [GEM_ROOT]/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
    transactional_request.rb 8 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/transactional_request.rb:8:in `create'
    actor_stack.rb 22 create(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/actors/hyrax/actors/actor_stack.rb:22:in `create'
    create_work_job.rb 19 perform(...)
    [GEM_ROOT]/bundler/gems/hyrax-7eed6a8326a0/app/jobs/create_work_job.rb:19:in `perform'
    execution.rb 34 block in perform_now(...)
    [GEM_ROOT]/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now' 
```

**Comment by jeremyf** [comment]
@jcoyne It looks more like there are two attempts to create the Sipity::Entity for the work.
